version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  evaluation_set:
    level: DEBUG
    handlers:
      - console
    propagate: false
  scripts:
    level: DEBUG
    handlers:
      - console
    propagate: false
  httpx:
    level: WARNING
    handlers: []
    propagate: false
  google_genai:
    level: WARNING
    handlers: []
    propagate: false
  __main__:
    level: DEBUG
    handlers:
      - console
    propagate: false
    
root:
  level: INFO
  handlers:
    - console